#!/bin/bash
nslookup who.int 8.8.8.8

# https://www.cyberciti.biz/faq/how-to-find-out-what-my-dns-servers-address-is/
# https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup
