#!/bin/bash
ipconfig getpacket en0 | grep yiaddr | cut -d " " -f3

# Dynamic Host Configuration Protocol (DHCP)
# DHCP server maintains a database of leased IP addresses, and assigns IP addresses (yiaddr)
# Specifies a network mask and a default gateway to use to access the Internet
