#!/bin/bash
echo "Choose an option (1-3):"
echo "1 Update and upgrade all packages"
echo "2 List all installed packages (press q to exit list)"
echo "3 Show the number of installed packages"
read option
if [ "$option" == "1" ]; then
	sudo apt-get -y update && sudo apt-get -y upgrade
	fi
if [ "$option" == "2" ]; then
	sudo dpkg-query -l | less
	fi
if [ "$option" == "3" ]; then
	sudo dpkg-query -W | wc -l
	fi
